name: CI/CD for VPS

on:
  push:
    branches:
      - main  # Trigger khi có commit vào nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cài đặt Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Cài đặt SSH để kết nối với VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 4. Build Docker images
      - name: Build Docker Images
        run: |
          docker-compose -f docker-compose.prod.yml build

      # 5. Triển khai lên VPS
      - name: Deploy to VPS
        env:
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          sshpass -p "$VPS_PASSWORD" -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VPS_NAME}}@${{ secrets.VPS_IP }} "
            cd basospark &&
            git pull origin main &&
            docker-compose -f docker-compose.prod.yml down &&
            docker-compose -f docker-compose.prod.yml up -d --build
          "
